### ISSUE TITLE
TWS Java 9 Broken

### ISSUE THREAD

**Issue by benalexau** [InteractiveBrokers/tws-api-public#7]
I know this is the TWS API project and not TWS itself, but I assume the IB folks here are all part of the same team.

Java 9 is due for release in July 2017. Many users (eg Linux, Docker etc) use TWS with a platform-provided JRE (not the Install4J-shipped JRE). As such after July 2017 these users will start to experience breakages with TWS if it isn't Java 9 compatible.

In the long-term IB will probably upgrade its redistributed JRE to Java 9 anyway in order to meet customer expectations around the latest available platform security fixes. As such moving forward with minor, non-breaking and backward-compatible changes that ready TWS for Java 9 compatibility is useful preparatory engineering.

I have been testing TWS 964.1 with Java 9-ea+160 on x86_64 Linux. I have found two issues which IB might wish to resolve:

# Access Modifier Change

Due to the Java 9 [strong encapsulation of APIs in non-exported packages invoked through setAccessible()](http://mail.openjdk.java.net/pipermail/jdk9-dev/2016-November/005276.html), loading TWS yields:

```
java.lang.reflect.InaccessibleObjectException: Unable to make private static javax.swing.UIManager$LAFState javax.swing.UIManager.getLAFState() accessible: module java.desktop does not "opens javax.swing" to unnamed module @2794eab6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:335)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:278)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:196)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:190)
	at feature.search.recorder.JtsMultiLookAndFeel.a(JtsMultiLookAndFeel.java:103)
	at twslaunch.jclient.login.a.d(a.java:376)
	at twslaunch.jclient.login.p.a(p.java:327)
	at jclient.LoginFrame.main(LoginFrame.java:423)
```

This can be worked around with a launch script that includes an `--add-opens` directive as follows:

```
$JAVA_HOME/bin/java --add-opens java.desktop/javax.swing=ALL-UNNAMED -cp \* -Xmx512M -XX:MaxPermSize=128M jclient.LoginFrame $HOME/.ib-tws
```

# Removal of Sun Internal APIs

Due to the Java 9 [removal of sun.misc.BASE64Encoder](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-F7696E02-A1FB-4D5A-B1F2-89E7007D4096), attempting to login yields:

```
java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
        at twslaunch.jauthentication.aM.b(aM.java:184)
        at twslaunch.jauthentication.aM.b(aM.java:165)
        at twslaunch.jsetting.I.v(I.java:1869)
        at twslaunch.jclient.login.p.d(p.java:748)
        at twslaunch.jauthentication.aT.c(aT.java:468)
        at twslaunch.jauthentication.aT.b(aT.java:431)
        at twslaunch.jauthentication.aT.a(aT.java:416)
        at twslaunch.jconnection.y.c(y.java:779)
        at twslaunch.jconnection.y.a(y.java:734)
        at twslaunch.jconnection.w.a(w.java:434)
        at twslaunch.jconnection.w.a(w.java:298)
        at twslaunch.jconnection.w.a(w.java:272)
        at twslaunch.jconnection.w.l(w.java:268)
        at twslaunch.jconnection.w.b(w.java:263)
        at twslaunch.jconnection.aw.a(aw.java:176)
```

There is no workaround, so this is a hard failure that prevents further testing.

I would be grateful if the TWS team would switch use of `BASE64Encoder` to the Java 1.8-included [Base64](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html) class. This should be a very quick and easy change for them to make and poses no backward compatibility risks.

I understand IB probably don't have the resources to test Java 9 compatibility and I do not propose that you commit to. I just ask that you replace the internal Sun `BASE64Encoder` class usage with the JDK `Base64` class so that I can test further and let you know of any other hard breakages encountered with Java 9. Thanks for your assistance.

**Comment by ksmaguineib** [comment]
IB only supports running TWS with the JRE installed by install4j. We will evaluate/decide when and how to transition to Java 9 after it is officially released, not while it is in beta
